# Arrays in Python

Besides lists, python also has arrays, which are list of elements of the same type

In [11]:
l=[2345, 27, 546, 215, -1234]

In [12]:
import numpy as np

In [13]:
a=np.array(l)
a

array([ 2345,    27,   546,   215, -1234])

In [7]:
b= np.array([12,455,63.3,True,'abc'])

In [8]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

All have been converted to strings, which is a type that can accomodate all of them, in order to have the same type for all elements

In [9]:
type(b)

numpy.ndarray

---

## Array slicing
This creates a reference to the original array, so modifying the original, modifies the slice.

In [10]:
a

array([ 2345,    27,   546,   215, -1234])

In [14]:
b

array(['12', '455', '63.3', 'True', 'abc'], dtype='<U32')

In [15]:
c = a[2:4]
c

array([546, 215])

In [17]:
c[0]

np.int64(546)

In [19]:
c[:]

array([546, 215])

In [20]:
c[:] = 111
c

array([111, 111])

In [21]:
a

array([ 2345,    27,   111,   111, -1234])

Array a has been modified through the slice c

In [23]:
d = a.copy()
d

array([ 2345,    27,   111,   111, -1234])

In [24]:
# modify d
d[0]= 0
d

array([    0,    27,   111,   111, -1234])

In [25]:
# a stays the same
a

array([ 2345,    27,   111,   111, -1234])