In [18]:
import numpy as np
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [19]:
#profit for each month
profit = np.subtract(revenue,expenses)
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [20]:
# profit after tax of 30%
profit_after_tax = profit * 0.7
profit_after_tax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [21]:
# profit margin for each month - equals to profit after tax divided by revenue
profit_margin = np.divide(profit_after_tax, revenue)*100
profit_margin

array([ 12.11616324,  17.58995643, -30.13969838, -22.23352417,
        -5.21109615,  62.74388559,  49.99343266,  28.27619856,
        22.60844884, -10.89749207,   4.30951365,  52.74680403])

In [22]:
# good months - where the profit after tax was greater than the mean for the year
good_months = profit_after_tax > profit_after_tax.mean()
good_months

array([ True, False, False, False, False,  True,  True,  True,  True,
       False, False,  True])

In [23]:
# bad months - where the profit after tax was less than the mean for the year
# I do not agree with these being the oposite to good_months: one month can be an average month
bad_months = profit_after_tax < profit_after_tax.mean()
bad_months

array([False,  True,  True,  True,  True, False, False, False, False,
        True,  True, False])

In [24]:
# the best month - where the profit after tax was max for the year
best_month = profit_after_tax == profit_after_tax.max()
best_month

array([False, False, False, False, False, False, False, False, False,
       False, False,  True])

In [25]:
# the worst month - where the profit after tax was min for the year
worst_month = profit_after_tax == profit_after_tax.min()
worst_month

array([False, False,  True, False, False, False, False, False, False,
       False, False, False])

In [26]:
# Presentation of the $ values
np.divide(profit,1000).round()
#profit_after_tax
np.divide(profit_after_tax,1000).round()
#profit_margin
np.round(profit_margin,2)

array([ 12.12,  17.59, -30.14, -22.23,  -5.21,  62.74,  49.99,  28.28,
        22.61, -10.9 ,   4.31,  52.75])

In [27]:
profit_after_tax.mean()

np.float64(1750.6813333333332)

In [28]:
profit_after_tax.sum()

np.float64(21008.176)